import Head from 'next/head'
import axios from 'axios'

const data ={
  email: 'test@consul-sts.com',
  password: 'password'
}

export default function Home() {
  const obtenerToken =async ()=>{
      axios.post('https://auth.consul-sts.com/auth/signin',data)
      .then(res=>{
        console.log(res)
        console.log(res.data)
      })
      .catch(error=>{
        console.log(error)
      })
      
  }

  return ( //Objeto JSX
    <>
      <Head>
        <title>Grupo2 | Servicios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={obtenerToken}>Obtener Token</button>

    </>

  )
}
