import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SectionServicios from '@/Componentes/SectionServicios'


export default function Home() {
//Codigo JS
    
    //Seccion
    //---Banner (titulo, descripcion)
    //---Card 1 (icono, titulo, descripcion)
    //---Card 2 (icono, titulo, descripcion)
    //---Card 3 (icono, titulo, descripcion)

  return ( //Objeto JSX
    <>
      <Head>
        <title>Grupo2 | Servicios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionServicios></SectionServicios>
    </>

  )
}
